name : Our First Workflow # 이름 생략시 파일 이름이 제목으로 설정됨
on : push #  on 속성을 통해서 해당 워크플로우가 언제 실행되는지를 정의합니다. - push는 main에 push가 발생할 경우 실행
jobs : 
  echa :
    runs-on: ubuntu-latest
    steps : # 값으로 시퀸스를 받는다, 순차적으로 실행할 단계를 적어도 1개 명시
      - run : echo 'Hello, GitHub Actions!'
  pwd-ls:
    name: PWD & LS
    runs-on : ubuntu-latest
    steps:
      - name : print working directory # 작업마다 이름 설정 가능
        run : pwd #pwd는 현제 경로를 출력해준다
      - name : List files
        run : ls -al # 현제 경로에 있는 모든 파일과 디렉토리를 나열해 준다
